### ISSUE TITLE
Unescaped double quote characters in csv files

### ISSUE THREAD

**Issue by pierre-an** [DFIR-ORC/dfir-orc#13]
Hi,

We have seen cases where the OriginalFileName field of the NTFSInfo CSV file contains double quote characters that are not escaped. Thus the NTFSInfo CSV file is unparseable.

Thanks.
Pierre

**Comment by jeanga** [comment]
Hi Pierre,
We are looking at this right now.
Thank you for this bug report.
Jean

**Comment by jeanga** [comment]
Hi Pierre,

A fix for this issue is now available in the dev branch.
Can you, please, confirm this issue is now fixed in your tests? :-)

Again, thank you very much for this bug report.
Jean

**Comment by fabienfl-orc** [comment]
81fc63345e972a2aa1653ba53e91b82207c24b17

Will be merged for upcoming 10.0.3
