### ISSUE TITLE
ExtractData - build standalone binary?

### ISSUE THREAD

**Issue by qlemaire** [DFIR-ORC/dfir-orc#19]
Hello,

Do you know whether it's possible to build a standalone binary for the ExtractData command during ORC compilation (like FastFind)? Probably via a cmake option `ORC_BUILD_EXRACTDATA` or by modifying CMakeLists.txt appropriately but I'm not familiar with cmake syntax :(

Thanks !

**Comment by fabienfl-orc** [comment]
It should be possible to remove all other commands from OrcCommand/CMakeLists.txt so you would have a standalone executable for few modifications.
I wish all commands could be compiled standalone, without any wrapper, but it requires more work to be done.
