### ISSUE TITLE
ORC config

### ISSUE THREAD

**Issue by lprat** [DFIR-ORC/dfir-orc#21]
Hi,

I would like create ORC config for extract ADS infos from all mounted NTFS, like this:
`
Get-Wmiobject -Class Win32_Logicaldisk | foreach-object { 
    $vol=$_.deviceID
    if ($_.FileSystem -like "NTFS") {
      try {
        if ($os -like "*32*") { 
			#32bits
			$sb = "$($currentPath)\streams.exe -accepteula -s $vol\ >> $($currentPath)/output/ADS-streams.log"
			iex $sb
		} else {
			$sb = "$($currentPath)\streams64.exe -accepteula -s $vol\ >> $($currentPath)/output/ADS-streams.log"
			iex $sb
		}
      } catch {
        echo "Error to create ADS for $vol"
      }
    }
  }
`

I dont find equivalent in ORC Conf:
`
 <command keyword="streams.exe">
            <execute name="streams.exe" run="7z:#Tools|streams.exe"/>
            <argument>-accepteula -s %SystemDrive%</argument>
            <output name="ADS-streams.log" source="StdOut"/>
            <output name="ADS-streams.err" source="StdErr"/>
 </command>
`

It's possible to extract streams.exe (from orc embeded) and run command powershell, like this:
`
<command keyword="Processes" winver="6.1+">
            <execute name="powershell" run="%SystemRoot%\System32\WindowsPowerShell\V1.0\powershell.exe"/>
            <argument>-NonInteractive -WindowStyle Hidden</argument>
            <argument>Get-Wmiobject -Class Win32_Logicaldisk | foreach-object { $vol=$_.deviceID if ($_.FileSystem -like "NTFS") { try { iex "$($extracted_path_from_orc)\streams.exe -accepteula -s $vol" } catch { echo "Error to create ADS for $vol" }}}</argument>
            <output name="ADS-streams.log" source="File" argument="-Path {FileName}"/>
            <output name="ADS-streams.err" source="StdOutErr"/>
        </command>
`

Second question, i would like to exract memory with winpmem.exe. This tool extract memory to file: "\winpmem.exe -t -dd --volume_format raw --format raw -o MEM_ram.raw". How to include the file generated by the tool 'MEM_ram.raw' in orc output archive (use source="File"?), and where write file "MEM_ram.raw" (%temp%)? 

Thanks.
Lionel

**Comment by lprat** [comment]
Sorry, i just saw that the ads information was already present in the ntfsinfo part that orc extracted.
Can you respond to my second question, please.
Thanks.

**Comment by jeanga** [comment]
Hi Lionel,
Thank you very much for your interest in dfir-orc!

Here is a brief example on how you can integrate winpmem in dfir-orc:
```xml
		<command keyword="winpmemv1" optional="yes" winver="6.3-" >
			<execute name="winpmem_1" run="7z:#Tools|winpmem_1" />
			<output name="Dump_winpmem1_{SystemType}_{FullComputerName}.ram" source="File" argument ="{FileName}" />
			<output name="Dump_winpmem1_{SystemType}_{FullComputerName}.log" source="StdOutErr" />
		</command>

		<command keyword="winpmemv2" optional="yes" winver="6.3-" >
			<execute name="winpmem-2" run="7z:#Tools|winpmem-2" />
			<output name="Dump_winpmem2_{SystemType}_{FullComputerName}.ram" source="File" argument ="--output {FileName}" />
			<output name="Dump_winpmem2_{SystemType}_{FullComputerName}.log" source="StdOutErr" />
		</command>
```

The output file name is created by the launcher (cf [output](https://dfir-orc.github.io/wolf_config.html#output-element))
Then, the -output argument is created with the concatenation of the temporary directory [temporary](https://dfir-orc.github.io/orc_local_config.html#temporary-element) with the filename (as per the attribute argument ="--output {FileName}").

Of course, you will also need to "embed" winpmem in your configured binary with:
```xml
        <archive name="Tools" format="7z" compression="Ultra">
		<file name="winpmem_1" path=".\tools\winpmem_1.6.2.exe" />
		<file name="winpmem-2" path=".\tools\winpmem-2.1.post4.exe" />
	</archive>
```

Regarding your question about the ADS collection, just a small warning, NTFSInfo will give you the name of any ADS present.
If you are looking into collecting the actual content of an ADS, GetThis is the tool you'll need [ntfs_find](https://dfir-orc.github.io/configuring_ntfs_opt.html#possible-attributes-of-a-ntfs-find-element)
 
Hope this will help you with your configuration.

**Comment by lprat** [comment]
Thank you for your prompt response. 
The solution works perfectly!

**Comment by lprat** [comment]
Sorry, one question yet!
It's possible to extract MFT & USN in raw format?
Thanks.

**Comment by jeanga** [comment]
[GetThis](https://dfir-orc.github.io/GetThis.html) is kind of the swiss knife of data collection in dfir-orc.
It should be able to handle most of your NTFS related collection tasks.
You just need to specify the appropriate [ntfs_find ](https://dfir-orc.github.io/configuring_ntfs_opt.html) statement to collect all your desires.

**Comment by jeanga** [comment]
dfir-orc also provides USNInfo that parses (and carves) USN journal entries for you.

**Comment by lprat** [comment]
Ok thank you very much.
