### ISSUE TITLE
Decrypt dfir-orc archives using linux

### ISSUE THREAD

**Issue by lprat** [DFIR-ORC/dfir-orc#22]
Sorry, i cannot reopen issue 6.
I would extract valid archive 7z from "jrnl" format with linux.
Have you solution?

Thank you
Lionel

**Comment by sc-anssi** [comment]
Hi,
We are in the process of publishing a tool to do just that. It should be coming soon.
Thanks for your patience !
Regards.

**Comment by sc-anssi** [comment]
Hi,
We published our tool at this address : https://github.com/DFIR-ORC/orc-decrypt
If you didn't encrypt your archive, then all you need is the `unstream` command (compile it with the Makefile provided in the repository)
Don't hesitate to open an issue on the orc-decrypt repository if you have some trouble to make it work.
Regards.
