### ISSUE TITLE
Cmake error Visual Studio 2019

### ISSUE THREAD

**Issue by FluffyAlpaca** [DFIR-ORC/dfir-orc#27]
Hello,
I'm using the Micorsoft's virtual machine for development, downloaded a month ago. On it, Visual Studio 2019 16.7.3 is preinstalled.
I did the import with the ".vsconfig"  given in the ORC installation procedure and followed the rest of the instructions. 

However, when I do the following command : 
`cmake -G "Visual Studio 16 2019" -A Win32 -T v141_xp ..`
I got the following error : 

> CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find VisualStudio (missing: CPPUNITTEST_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVisualStudio.cmake:62 (find_package_handle_standard_args)
  external/vcpkg/scripts/buildsystems/vcpkg.cmake:331 (_find_package)
  src/OrcLib/CMakeLists.txt:17 (find_package)

Do you have an idea where it may come from ?  Don't hesitate to ask if you need more details. 
Thank you.

**Comment by fabienfl-orc** [comment]
Hello, can you check within Visual Studio Installer that the highlighted item below is checked ?

Thank you

![image](https://user-images.githubusercontent.com/55688171/92944073-d3bc0900-f453-11ea-9ca3-851bb06e0a51.png)

**Comment by FluffyAlpaca** [comment]
This item was indeed not checked. I checked it and the compiling ended without errors, thank you for our help !
