### ISSUE TITLE
x64 Compilation error (C3859 / C1076)

### ISSUE THREAD

**Issue by BoubouPaquerette** [DFIR-ORC/dfir-orc#32]
Hello,

I have some issue to compiling DFIR-ORC. The error appear with the command `cmake --build . --config MinSizeRel -- -maxcpucount`

Furthermore, I followed the step on Tutorial - Build ; and I had issue on the directory created: "build-x86". It's empty, so I ran the command `make -G "Visual Studio 16 2019" -A x64` under the project directory (root) to do that works.

I use Microsoft Visual Studio Community 2019 - Version 16.8.3

Errors:
> c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : the system returned code 1455: Le fichier de pagination est insuffisant pour terminer cette opération. [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.v
cxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  hash_stream_test.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  fuzzy_hash_stream.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  structured_output_test.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  running_code_test.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  authenticode_test.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  locations.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  yara_basic.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  yara_scanner.cpp
  table_output.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
  buffer.cpp
c1xx : error C3859: Failed to create virtual memory for PCH [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : PCH: Unable to commit memory across file map [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : message : please visit https://aka.ms/pch-help for more details [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [C:\Users\abc\source\repos\dfir-orc_x64\tests\OrcLibTest\OrcLibTest.vcxproj]

**Comment by jeanga** [comment]
I have the impression that your machine does not have enough physical memory available (and/or paged île) .

**Comment by BoubouPaquerette** [comment]
Hi Jeanga,

:/ I've 8Go memory, that's not enought?

**Comment by BoubouPaquerette** [comment]
Hi Jeanga,

Ok it works!

Thank you 👍
