### ISSUE TITLE
GetSamples: enable autorunsc for all users with '-a *'

### ISSUE THREAD

**Issue by lprat** [DFIR-ORC/dfir-orc#33]
Hi,
Option to run autorunsc maybe not complet:
https://github.com/DFIR-ORC/dfir-orc/blob/932588cc1fde69c3d4a187c1d187d92b7bec91e0/src/OrcCommand/GetSamples_Run.cpp#L79

Add "*" at end for all user.
```
Usage: autorunsc [-a <*|bdeghiklmoprsw>] [-c|-ct] [-h] [-m] [-s] [-u] [-vt] [[-z ] | [user]]]
user Specifies the name of the user account for which autorun items will be shown. Specify '*' to scan all user profiles.
```

Thanks,
Lionel

**Comment by fabienfl-orc** [comment]
Merged for 10.0.19 and 10.1.0-rc6.

Thank you
