### ISSUE TITLE
error compilation

### ISSUE THREAD

**Issue by Fp210315** [DFIR-ORC/dfir-orc#38]
Hello,

I use a vm with .vsconfig. But i alaways the same error :

Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.

....

Error: Building package bzip2:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

**Comment by fabienfl-orc** [comment]
Hello,
The chosen mirror for mingw seems offline. Could you try another time from a new directory please ?
This fails on a dependency requirement, it seems to select a mirror from China...

**Comment by Fp210315** [comment]
Hello,

Thanks 
Now i have a new error: 
-- Found Boost: C:/anssi/dfir-orc/external/vcpkg/installed/x64-windows-static/include (found version "1.73.0")
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find VisualStudio (missing: CPPUNITTEST_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVisualStudio.cmake:81 (find_package_handle_standard_args)
  external/vcpkg/scripts/buildsystems/vcpkg.cmake:555 (_find_package)
  src/OrcLib/CMakeLists.txt:16 (find_package)
___________
I use the vm dev with the .vsconfig. I execute in the dev command Prompt.

Thank for your help

**Comment by fabienfl-orc** [comment]
Hello, the "vm dev" you are mentioning is the one provided by Microsoft ? Can you give me the address ?

**Comment by Fp210315** [comment]
Hello,

Here the link to microsoft

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/


De : fabienfl ***@***.***>
Envoyé : jeudi 29 avril 2021 14:13
À : DFIR-ORC/dfir-orc ***@***.***>
Cc : POREE Florent ***@***.***>; Author ***@***.***>
Objet : Re: [DFIR-ORC/dfir-orc] error compilation (#38)


Hello, the "vm dev" you are mentioning is the one provided by Microsoft ? Can you give me the address ?

**Comment by fabienfl-orc** [comment]
This error could relate to https://github.com/DFIR-ORC/dfir-orc/issues/27

**Comment by fabienfl-orc** [comment]
If #27 fixes your previous issue then be sure to build from a clean directory. As VS installation would be "partial", your old build artefacts from vcpkg would be incompatible with the newly built Orc binary (see eventually: https://github.com/DFIR-ORC/dfir-orc/issues/43 ).
