### ISSUE TITLE
Fastfind Unspecified error with hash of empty file

### ISSUE THREAD

**Issue by sydurand** [DFIR-ORC/dfir-orc#5]
Hello,

With FastFind, when I use ntfs_find to mach empty file by hash (md5, sha1 or sha26) I get the following error:
> ERROR (Unspecified error, hr=E_FAIL 0x80004005):
> Parsing record 0000000000000003 threw an exception
 
Example of configuration:
```
<ntfs_find sha256="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"/>
```

**Comment by jgautier-anssi** [comment]
Hi SyDurand,

Thank you for your issue with FastFind.
This error, as I understand it, should not prevent fast find from continuing it's search normally.
(i.e. the parsing of the third MFT entry failed for some reason)

I'll try to reproduce your issue and get back to you.
Thanks!
Jean

**Comment by jgautier-anssi** [comment]
OK, I reproduced and fixed the issue.
I have also improved the reporting for this error.
Expect a fix early next week.
Thanks again!

**Comment by fabienfl-orc** [comment]
Should be fixed in dev branch by multiple commits before 06e2b58e8195490d0501876dfda084e4a3f81093
