### ISSUE TITLE
Mapping VolumeID from NTFSInfo and USNInfo report with drive letter

### ISSUE THREAD

**Issue by nahotjan** [DFIR-ORC/dfir-orc#51]
Hello,

Both reports from NTFSInfo and USNInfo are using a VolumeID to identify the disk which is not easily mapped to a drive letter.
Having this information (drive letter for a VolumeID) displayed either in the volstats.csv file from NTFSInfo or DFIR_ORC json report could make sense.

Currently the information is visible in the log files but not well formatted. This can help during automated ingestion of Orc results for hosts having multiple drives.

**Comment by fabienfl-orc** [comment]
Hello, this information should be available in the upcoming version from the volstats.csv file.
Thank you

**Comment by nahotjan** [comment]
Good to know 👍 
Thank you
