### ISSUE TITLE
Feature request - allow authentication without a clear text password in upload balise from the local config file 

### ISSUE THREAD

**Issue by CERT-ENEDIS** [DFIR-ORC/dfir-orc#53]
Hello,

Assuming no transparent authentication or public share is available, is it possible to implement a kind of mechanism to avoid clear text password in the upload balise in the local configuration file ?

Thank for you job

Cert-Enedis

**Comment by CERT-ENEDIS** [comment]
Hello,

We understand the point, to comment our need, in our contexte we need to setup a permanent infrastructure with a "ready to deploy and collecte orc configuration" on multiples endpoints.
- We can't use transparent authentication (reasons not developped here)
- We want to keep in one opération (with orc) the execution and the upload of the archive.

At this time, we use the archive level encryption and are ready to assume the risk of a clear text password with the "minimal privileges policy" but it will be a nice to have feature to be able to authenticate without a clear text password.

Regards,

CERT ENEDIS

**Comment by jgautier-anssi** [comment]
Hi,

Regarding the need for "ready to deploy" infrastructure, may be the user account can be disabled "by default" and only enabled when needed?

We will keep in mind your requirement when we design future versions of dfir-orc.

Thank you for your feedback. 
Best regards,
Jean Gautier
