### ISSUE TITLE
Zircolite Integration

### ISSUE THREAD

**Issue by ZikyHD** [DFIR-ORC/dfir-orc#54]
I am trying to integrate [Zircolite](https://github.com/wagga40/Zircolite) in the DFIR Orc configuration.
However, there seems to be a problem when the main executable tries to use the [evtx_dump](https://github.com/omerbenamram/evtx) binary.
![zircolite_exec](https://user-images.githubusercontent.com/10797142/141683969-71872658-2276-42d1-806b-01e417d367ae.png)
Config:
![dfir_orc_config](https://user-images.githubusercontent.com/10797142/141683984-5a56aea2-d698-4801-8731-7731500616db.png)
Indeed, the extracted binary (indicated in [input](https://dfir-orc.github.io/wolf_config.html#input-element) argument and added in tools folder) doesn't seem to be executable and the execution comes back with errors.
![evtx_dump](https://user-images.githubusercontent.com/10797142/141684246-9fa7d915-889f-496a-827d-eb7b3d4b6513.png)

**Comment by fabienfl-orc** [comment]
Hello, fix should be merged in upcoming 10.0.22

**Comment by fabienfl-orc** [comment]
Will be fixed also on upcoming 10.1.0-rc8

**Comment by ZikyHD** [comment]
> Hello, fix should be merged in upcoming 10.0.22

Just tested and it's now ok. Thanks 😉
