### ISSUE TITLE
Unable to decrypt (encrypted) DFIR-Orc archives

### ISSUE THREAD

**Issue by tazrome** [DFIR-ORC/dfir-orc#6]
Hello,

Big thanks for release this tool.

I have an issue and i can't find how to solve it. I compiled with no error the two mothership executable both 64 et x86. I am able to build simple or more complexe configured binary files however the only way to run the configured binary file is with a command line. Running the binary by double-clicking on it or with a taskscheduler result in a failure.

I see in the documentation 

> "The Mothership mechanism allows DFIR ORC to be executed in any compatible context (Scheduled Task, Logon Script, Startup script, x86/x64…). The configuration allows the Mothership to launch the subsequent execution which suits the context. Specific command-line options can be used to customize this behavior." 

I haven't success to pass argument like _NoWait_, _WMI_ or _PreserveJob_ to the mothership. I have at this time no idea why the execution failed if i double-click on exe file and why it successed if i run it from cmd.exe

please see below the screenshot of failure (At this time, i have no more details)

![failed_1](https://user-images.githubusercontent.com/57143514/67779025-5dddc780-fa64-11e9-91b3-cd28a8eac621.png)
![failed_2](https://user-images.githubusercontent.com/57143514/67779032-60d8b800-fa64-11e9-85fb-62011a7aee17.png)

Feel free to ask any information needed for debugging purpose.

Apologize for a non correct english syntax

Regards

**Comment by md-anssi** [comment]
Hello tazrome,
Thank you for your interest in our project.
Concerning your problems, just to check, can you first confirm that you are running DFIR ORC with administrative privileges? In particular in the case of the scheduled task, did you set it to execute as SYSTEM? (On a side note, do not forget to set the directory where you get your results, otherwise, it is Windows/System32, which should not be polluted...).
Besides, especially for the double-clicking scenario, can you test whether this still occurs with the last version (published 7 days ago)? We ran into a similar problem and fixed it recently. 
Thank you for your feedback, please let us know if it is sufficient to solve all your problems.
Cheers,

**Comment by tazrome** [comment]
Hello,

Thank for your reply, i make a new pull request on master, recompile mothership and it's good now, the problem disapears. Great

PS: I'm not able to decrypt an archive with pkcs7-envelopped data. The archive seems well-formed but openssl endup with a "bad decrypt" (i have also try Unprotect-CMSMessage with powershell and no success). Is there any problem known about it ? Maybe do I need to open a new issue about it ?

Thank you for this new version, it solved my inital issue.

regards

**Comment by md-anssi** [comment]
Hi,
Sorry, our mistake, the encrypted archives cannot be decrypted right away. There is a proprietary algorithm used to build encrypted archives in a write-only manner, and this has to be undone at decryption. We'll come back to you at the beginning of next week with a usable solution.

**Comment by jeanga** [comment]
Hi tazrome,
md-anssi is correct the decrypted cms file is not directly the 7z archive. To enable the pkcs7 streaming, we had to trick 7z library. However, openssl should have been able to decrypt the message. This error is surprising... 
Can you share information on the version of Openssl you are using and how you generated your test certificate? 

As previously said, we'll get back to you with a workable solution for you.

**Comment by tazrome** [comment]
Hi,

I have tested with OpenSSL 1.0.2g 1 Mar 2016 and  OpenSSL 1.1.1a 20 Nov 2018.
The certificate was generated basically with command like

`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem`

The cert file include the encrypted private key and the public key. Certificate is PEM formated (apparently it's mandatory to use the -recip option for OpenSLL smime)

I tried decryption with `-recip` option or directly with `-inkey` option (with private key). Each try ends with a "bad decrypt" (except for the printed output with cmder .... don't understand why ....)

I have tested with a lot of options (binary, stream, ect, ...) and output formats (DER, PEM, ...). Each decryption start and produce a truncated file (never the same although the parameters was the same) and end with a "bad decrypt" message.
The size of the truncated file is different if I try with a new certificate as if the failure appears later or sooner.
 
some details on the screenshots below

![error_output](https://user-images.githubusercontent.com/57143514/68131671-bbb75700-ff1d-11e9-9a29-4c63fd118249.PNG)

![error_output_cmd](https://user-images.githubusercontent.com/57143514/68131678-bd811a80-ff1d-11e9-9ddc-9634fe4ba61f.PNG)

![no_error_output](https://user-images.githubusercontent.com/57143514/68131684-beb24780-ff1d-11e9-9a80-43cae11bbab8.PNG)

PS: I have also tested with certificate generated from powershell with the help of windows cert store or not ...

Thank you

**Comment by rg-anssi** [comment]
Hello tazrome,

Can you please try with the "cms" command of openssl?
For example:
```
openssl cms -decrypt -in my_archive.7z.p7b -inform DER -inkey key.pem -binary -out my_archive.7z
```
Can you confirm that you don't have any errors (even if the result - my_archive.7z - is not a valid 7z archive)?
Next, we will give you a solution to process this file to generate a valid 7z archive.

Cheers

**Comment by tazrome** [comment]
Ooooh it works.... sorry, my bad i did not see the `cms` command.

The output file seems correct, i can see some kind of header like JRNL and others information like SEEK or WRIT so the decryption process is probably Ok.

I'm waiting for the next step

Thank you

**Comment by jgautier-anssi** [comment]
Hello tazrome,

Nice to see you have been able to decrypt the PKCS#7 content of the archive.
From you comment, the tags you are seeing confirm correct decryption of the stream and a valid '7z journal' file. 

There is definitively a gap in our documentation on this (openssl correct command line) as well as missing tool information.

We are working on publishing those asap and we appreciate your patience.
We hope that this does not prevent you from testing other DFIR-Orc functionalities.
We're looking forward to read what you will be able to do with these tools.

Please keep the great feedback coming!
Jean

**Comment by fabienfl-orc** [comment]
Hello tazrome,

I have added the command 'extractdata' into dev branch since 003fce1f9fa7aec53fe89d04c0145d6975cc40ee

This command is a work in progress and will have more options later. Currently it is only supporting *Microsoft Security Cryptography Service Provider* and the keys have to be imported under user's certificate store (use 'certmgr.msc').

Here is an extraction command line example:
```
.\dfir-orc_x64.exe extractdata prod.p7b /out=c:\extract
```
This should output some 7z files in `c:\extract`

**Comment by tazrome** [comment]
Hello,

It's Ok, perfect. I'm waiting for the others features : )
Thks for the help

Regards

**Comment by jeanga** [comment]
Thank you for the good news and feedback!
Keep us posted on any difficulty you may have with dfir-orc.

**Comment by lprat** [comment]
Hi,
Have you a command linux (or python script) to extract/repair p7b (after openssl cms result)?
Thank,
Lionel

**Comment by fabienfl-orc** [comment]
Prefer using https://github.com/DFIR-ORC/orc-decrypt
